services:
  - type: web
    runtime: static
    name: weirdm
    branch: mane
    buildCommand: ""
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
